/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaccineRouteImport } from './routes/vaccine'
import { Route as DrugsRouteImport } from './routes/drugs'
import { Route as IndexRouteImport } from './routes/index'

const VaccineRoute = VaccineRouteImport.update({
  id: '/vaccine',
  path: '/vaccine',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsRoute = DrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drugs': typeof DrugsRoute
  '/vaccine': typeof VaccineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drugs': typeof DrugsRoute
  '/vaccine': typeof VaccineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drugs': typeof DrugsRoute
  '/vaccine': typeof VaccineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drugs' | '/vaccine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drugs' | '/vaccine'
  id: '__root__' | '/' | '/drugs' | '/vaccine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrugsRoute: typeof DrugsRoute
  VaccineRoute: typeof VaccineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaccine': {
      id: '/vaccine'
      path: '/vaccine'
      fullPath: '/vaccine'
      preLoaderRoute: typeof VaccineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs': {
      id: '/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrugsRoute: DrugsRoute,
  VaccineRoute: VaccineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
